apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}
  labels:
    app: {{ $.Release.Name }}
spec:
  replicas: 3
  template:
    metadata:
      name: {{ $.Release.Name }}
      labels:
        app: {{ $.Release.Name }}
    spec:
      containers:
        - name: {{ $.Release.Name }}
          image: nginx:1.9-alpine
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: {{ $.Release.Name }}
